- name: loops in/uin
  hosts: all
  tasks:
    - name: install s/w
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree,b: present,c: yes}
        - {a: maven,b: present,c: no}


