---
- name: Configuring apache2
  hosts: all
  tasks:
    - name: Install apache2 on all servers
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Edit the idnex.hmtl file
      copy:
        content: "IntelliQ"
        dest: /var/www/html/index.html
    - name: Restar apache2
      service:
        name: apache2
        state: restarted
    - name: Check apache response on server1
      uri:
        url: http://172.31.27.65
        status_code: 200
    - name: Check apache response on server2
      uri:
        url: http://172.31.26.107
        status_code: 200
...
